### ISSUE TITLE
Plugin return "Your new balance is now 0.0

### ISSUE THREAD

**Issue by XLuma** [Huskehhh/Shop-by-Conjurate#1]
Hi !
I tried the plugin earlier today to add shops to my server. Unfortunately, when I'm trying to link pages between them, all i get is a message sayins Your new balance is now 0.0
Steps:
1: Create a page named Menu, and the other however you want
2: do /shop page manage menu
3: do /shop page edit, and add the item to the inventory. Left-click it, set the function as a command, and add the command shop page open [name of the page you created after menu]
4: Close the editor, open Menu by /shop page open menu and try accessing your newly added page. Plugin should return "Your new balance is 0.0"

This is not supposed to happen, as it is supposed to open the other shop page. Tested on SpigotMC 1.14.4

**Comment by Huskehhh** [comment]
Hey there and thank you for the report. I've since fixed the error! It should be in the newest build from: https://ci.husk.pro/job/Shop-By-Conjurate/

Should you come across any other bugs please don't hesitate to let me know :)

**Comment by XLuma** [comment]
Re-opening this, the fix doesn't seems to be working. Latest build, Spigot minecraft 1.14.4 (althought the gui bug reported by another user is fixed)

**Comment by XLuma** [comment]
Also it no longer shows the "New balance", but the command just wont work.

**Comment by Huskehhh** [comment]
> Re-opening this, the fix doesn't seems to be working. Latest build, Spigot minecraft 1.14.4 (althought the gui bug reported by another user is fixed)

I can't replicate this, it works fine either through menu or by command. Are you able to provide some more information?

**Comment by Huskehhh** [comment]
Closing as I haven't heard back in a week :)
